### ISSUE TITLE
Request to join pattern house

### ISSUE THREAD

**Issue by Aztech07** [openAOD/Join_PatternHouse#44]
GitHub Username; Aztech07

I want to be a part of the organization in order to get knowledge about Open Source. I would like to contribute to your organization and learn new skills and have a good experience while learning and contributing to the project.

I would like to contribute the patterns in C++, because I'm quite comfortable in that.

**Comment by aryashah2k** [comment]
sent an invite, let m eknow if you are a participant of the ongoing SWOC open source program or a normal contributor
